# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "ZhikangNiu"
repo_name: "speech-arxivâ€”daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/speech-arxiv-daily.json'
json_gitpage_path: './docs/speech-arxiv-daily-web.json'
json_wechat_path: './docs/speech-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Text to Speech":
        filters: ["TTS", "Speech Synthesis", "Text to Speech", "Voice Synthesis", "Speech Generation", "Neural Speech Synthesis", "Neural TTS"]
    "Music Generation":
        filters: ["Music Generation", "Text to Music"]
    "Text to Audio":
        filters: ["Text to Audio", "TTA", "Audio Generation", "Audio Synthesis"]
    "Video to Audio":
        filters: ["Video to Audio", "V2A", "Audio-Visual", "Video Dubbing"]
    "Voice Conversion":
        filters: ["Voice Conversion", "VC", "Voice Cloning", "Voice Morphing"]
    "Editing":
        filters: ["Speech Editing", "Audio Editing", "Music Editing"]
    "Video Generation":
        filters: ["Video Generation", "T2V","Video Synthesis"]
    "Image Generation":
        filters: ["Image Generation", "T2I", "Image Synthesis"]
    "CV Editing":
        filters: ["Video Editing", "Image Editing"]
    "Audio Codec":
        filters: ["Audio Codec", "Audio tokenizer", "Speech tokenizer", "Speech codec", "Speech codecs"]
    "Large Audio Language Model":
        filters: ["Large Audio Language Model", "LALM", "ALM", "Omni", "omni model"]
